version: "3.9"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: quotes-generator
        volumes:
            - '.:/app'
        ports:
            - "81:80"